//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пиво
    {
        public int id { get; set; }
        public double Вміст_алкоголю { get; set; }
        public int IPA { get; set; }
        public string Тип_пива { get; set; }
    
        public virtual Типи_пива Типи_пива { get; set; }
        public virtual Пивовар Пивовар { get; set; }
    }
}
