//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пивовар
    {
        public int id { get; set; }
        public string Псевдонім { get; set; }
        public System.DateTime Дата_народження { get; set; }
        public byte Роки_досвіду { get; set; }
        public string Пиво { get; set; }
    
        public virtual Пиво Пиво1 { get; set; }
        public virtual Список_замовлень Список_замовлень { get; set; }
    }
}
