//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Типи_пива
    {
        public int id { get; set; }
        public string Назва { get; set; }
        public string Характеристика { get; set; }
    
        public virtual Пиво Пиво { get; set; }
    }
}
